services:
  webserver:
    build: .
    image: kirby-docker
    container_name: webserver
    ports:
      - "8080:80"
      - "9000:9000"
    volumes:
      - .:/var/www/html/
    env_file:
      - ./id.env
